[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"


[dependencies]
getrandom = { version = "0.2.7", features = ["js"] }
grid = "0.9"
log = "0.4"
rand = "0.8.5"
yew = { version = "0.20", features = ["csr"] }
yew-agent = "0.2"
wasm-logger = "0.2"
